server:
  context-path: /
  port: 10001

spring:
  rabbitmq:
    addresses: localhost
    username: admin
    password: 123456
    connection-timeout: 3000
    template:
      receive-timeout: 3000
    listener:
      simple:
        concurrency: 5
        max-concurrency: 20
        acknowledge-mode: manual
        retry:
          enabled: true
    cache:
      channel:
        size: 10
        checkout-timeout: 10000
