server:
  context-path: /
  port: 10008

spring:
  rabbitmq:
    addresses: rabbitmq.gs.liaodaotiyu.com:5672
    username: ldadmin
    password: D44u8rGi
    connection-timeout: 3000
    template:
      receive-timeout: 3000
    listener:
      simple:
        concurrency: 5
        max-concurrency: 20
        acknowledge-mode: manual
        retry:
          enabled: true
    cache:
      channel:
        size: 10
        checkout-timeout: 10000
